### PR TITLE
refactor: format files using prettier

### PR DESCRIPTION
**Pull request by abumalick**

### CODE REVIEW

**Comment by abumalick** [comment]
here you go for the prettier PR @sgtsquiggs

**Comment by abumalick** [comment]
Do you want me to update Adhan.js? @sgtsquiggs

**Comment by sgtsquiggs** [comment]
Yes please!

**Comment by sgtsquiggs** [comment]
Can you also retarget this MR to `develop` branch

**Comment by z3bi** [comment]
@abumalick the checks are failing because Adhan.js doesn't contain the latest changes. Please run "npm run build" and add Adhan.js and Adhan.js.map to your commit.

**Comment by abumalick** [comment]
@sgtsquiggs @z3bi  do you want me to config prettier as a precommit hook?

**Comment by z3bi** [comment]
> @sgtsquiggs @z3bi do you want me to config prettier as a precommit hook?
> https://prettier.io/docs/en/precommit.html

Yeah that would be great. We use Husky for our current githooks.

**Comment by abumalick** [comment]
Here you go, this configuration will format automatically the files before committing them. I added the generated build files to `.prettierignore` file to avoid formatting them

**Comment by z3bi** [comment]
@abumalick please also add the `shared/` directory to ignore as well since they are brought in from another repo.

**Review by sgtsquiggs — APPROVED** [review]

**Pull request merged**
