### PR TITLE
Adding the Moroccan method

### PR DESCRIPTION
**Pull request by Kafiil**
I opened an issue with more details to discuss this.
You can see more details here #12 .
Let me know what you think.

### CODE REVIEW

**Comment by z3bi** [comment]
Thank you for the PR. At the very least we should add a unit test that compares the prayer times generated with a known set from an official source (like http://www.habous.gov.ma) and ideally we want to create full set of times to compare against (see https://github.com/batoulapps/adhan-js/tree/master/Shared/Times) These files have one set of prayer times for each of month of the year. This is because it's important to test each season as the sunrise and sunset angles have the most extreme values in the summer solstice and winter solstice. Without testing both its easy to think the times match but that only being true for one part of the year.

**Comment by Kafiil** [comment]
https://maroc-salat.herokuapp.com/prayer?cityId=80&day=1&lang=fr-fr

This is the data for Marrakech for each first day if the month for the whole year

**Comment by z3bi** [comment]
Thanks for adding the year round comparison times. Looks great!

**Comment by Kafiil** [comment]
I am still not convinced with the calculationMethod.

I did a test with full year set of data, and it did only pass with `variance=5`

**Comment by z3bi** [comment]
@Kafiil can you post the full year file?

**Comment by Kafiil** [comment]
sure, do you want me to replace the current file ?

**Comment by z3bi** [comment]
Sure that works

**Pull request merged**
