### PR TITLE
Disable releaser dry-run flag

### PR DESCRIPTION
**Pull request by sgtsquiggs**

### CODE REVIEW

**Comment by sgtsquiggs** [comment]
@gimyboya double checking - this PR will cause the release?

**Comment by gimyboya** [comment]
@sgtsquiggs once you merge this to master semantic-release will start counting commits since the last tag. Which is at v4.0.3 if I am not mistaken.

For every fix commit semantic-release will bump the patch version number

For every feature commit it will bump the minor version number

If any commit has a breaking change then a new magore release will be released for instance 5.0.0

From what I see your commit is a ci commit so there shouldn't be any new release. (I am outside on my phone)

Please double check from the release action logs of the previous build if no new release then you are safe to go.

**Comment by gimyboya** [comment]
I think [this line](https://github.com/batoulapps/adhan-js/blob/master/.github/workflows/node.js.yml#L90) is causing a problem in the last build. I don't see its utility since Github actions come with npm pre-installed.

image

as for this PR the build was skipped all together (I am not sure why) I can't find a way to read `semantic-release` logs.

maybe omitting [this line](https://github.com/batoulapps/adhan-js/blob/master/.github/workflows/node.js.yml#L90) will be better? @sgtsquiggs

**Comment by sgtsquiggs** [comment]
@gimyboya that error was caused by me not `use`ing node-setup action before running npm install :expressionless: - i fixed it in a later commit

**Comment by sgtsquiggs** [comment]
Actually it's fixed here: #57

**Comment by gimyboya** [comment]
@sgtsquiggs looking at the last build logs `semantic-release` is ready to release the `V4.1.0` as you can see here

image


Merging this PR trigger a new release and new changelog (which I think it's fine)

**Review by z3bi — APPROVED** [review]

**Pull request merged**
