### PR TITLE
Using a whole year set of data for Casablanca/Morocco  to test the calculation method

### PR DESCRIPTION
**Pull request by Kafiil**

### CODE REVIEW

**Comment by Kafiil** [comment]
@z3bi as requested.

Do you think you can tweak the calculation method to bring the variance down to 1 or ideally 0 ? 

Thanks

**Comment by z3bi** [comment]
I see that the coordinates changed, what is the name of this region in the dropdown here? http://www.habous.gov.ma/fr/horaire-priere.html

**Comment by Kafiil** [comment]
Casablanca

**Comment by z3bi** [comment]
I think the json file is wrong. You have 
```  "times": [
    {
      "date": "2020-01-01",
      "fajr": "6:58 AM",
      "sunrise": "8:30 AM",
      "dhuhr": "1:36 PM",
      "asr": "4:11 PM",
      "maghrib": "6:33 PM",
      "isha": "7:53 PM"
    },```

but on the site I see:
```Casablanca | 1 / 2020
-- | --
Jour | Fajr | Chourouq | Dhuhr | Asr | Maghrib | Ishae
1 | 07:01 | 08:31 | 13:39 | 16:15 | 18:38 | 19:57


```

**Comment by Kafiil** [comment]
You're right. I fixed it.
And now the tests pass for `variance = 1`

**Comment by Kafiil** [comment]
I did a test with two more cities : Rabat and Oujda, but I don't think I should include them, otherwise tests would take so much time

**Pull request merged**
