### PR TITLE
v4.3.0

### PR DESCRIPTION
**Pull request by z3bi**

### CODE REVIEW

**Review by korbav — APPROVED** [review]
👍

**Comment by korbav** [comment]
@z3bi I'm sorry I just noticed we're not exporting the Shafaq object : 

```
const adhan = {
  Prayer: src_Prayer,
  Madhab: Madhab,
  HighLatitudeRule: src_HighLatitudeRule,
  Coordinates: Coordinates,
  CalculationParameters: CalculationParameters_CalculationParameters,
  CalculationMethod: src_CalculationMethod,
  PrayerTimes: PrayerTimes_PrayerTimes,
  SunnahTimes: SunnahTimes_SunnahTimes,
  Qibla: qibla,
  PolarCircleResolution: PolarCircleResolution,
  Rounding: Rounding
};
```

I think what we should do is the following: 

```
const adhan = {
  Prayer: src_Prayer,
  Madhab: Madhab,
  HighLatitudeRule: src_HighLatitudeRule,
  Coordinates: Coordinates,
  CalculationParameters: CalculationParameters_CalculationParameters,
  CalculationMethod: src_CalculationMethod,
  PrayerTimes: PrayerTimes_PrayerTimes,
  SunnahTimes: SunnahTimes_SunnahTimes,
  Qibla: qibla,
  PolarCircleResolution: PolarCircleResolution,
  Rounding: Rounding,
  Shafaq: Shafaq
};
```

**Comment by z3bi** [comment]
Yup, I definitely forgot to do that. Thank you.

**Comment by z3bi** [comment]
@korbav ok 4.3.1 should now be fixed

**Comment by korbav** [comment]
> @korbav ok 4.3.1 should now be fixed

It works great! Thank you

**Pull request merged**
