### PR TITLE
Rewrite in typescript

### PR DESCRIPTION
**Pull request by sgtsquiggs**
This is a placeholder PR that shouldn't be merged until after #98. All `ts` files come from #93.

Prefer this PR be redone by @abumalick for proper attribution!

### CODE REVIEW

**Comment by sgtsquiggs** [comment]
Fixes #100

**Comment by abumalick** [comment]
Thank you @sgtsquiggs , I will try to finish my PR today inchallah. I can use your changes to the rollup config from here right?

**Comment by sgtsquiggs** [comment]
> Thank you @sgtsquiggs , I will try to finish my PR today inchallah. I can use your changes to the rollup config from here right?

Yeah please mirror the configurations here - babel, eslint, tsconfig, rollup, and package.json

**Comment by abumalick** [comment]
Done, I did small changes to eslint configuration and package.json, please check it on https://github.com/batoulapps/adhan-js/pull/93 when you have time 👍🏻

**Pull request closed without merging**
